
package artifact;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LoadXMLService", targetNamespace = "http://webservice/", wsdlLocation = "http://localhost:8082/loadXML?wsdl")
public class LoadXMLService
    extends Service
{

    private final static URL LOADXMLSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOADXMLSERVICE_EXCEPTION;
    private final static QName LOADXMLSERVICE_QNAME = new QName("http://webservice/", "LoadXMLService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/loadXML?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOADXMLSERVICE_WSDL_LOCATION = url;
        LOADXMLSERVICE_EXCEPTION = e;
    }

    public LoadXMLService() {
        super(__getWsdlLocation(), LOADXMLSERVICE_QNAME);
    }

    public LoadXMLService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOADXMLSERVICE_QNAME, features);
    }

    public LoadXMLService(URL wsdlLocation) {
        super(wsdlLocation, LOADXMLSERVICE_QNAME);
    }

    public LoadXMLService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOADXMLSERVICE_QNAME, features);
    }

    public LoadXMLService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoadXMLService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LoadXML
     */
    @WebEndpoint(name = "LoadXMLPort")
    public LoadXML getLoadXMLPort() {
        return super.getPort(new QName("http://webservice/", "LoadXMLPort"), LoadXML.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoadXML
     */
    @WebEndpoint(name = "LoadXMLPort")
    public LoadXML getLoadXMLPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice/", "LoadXMLPort"), LoadXML.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOADXMLSERVICE_EXCEPTION!= null) {
            throw LOADXMLSERVICE_EXCEPTION;
        }
        return LOADXMLSERVICE_WSDL_LOCATION;
    }

}
