
package artifact;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LoadStatisticsService", targetNamespace = "http://soap.statistics.project3.is/", wsdlLocation = "http://localhost:8081/statistics?wsdl")
public class LoadStatisticsService
    extends Service
{

    private final static URL LOADSTATISTICSSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOADSTATISTICSSERVICE_EXCEPTION;
    private final static QName LOADSTATISTICSSERVICE_QNAME = new QName("http://soap.statistics.project3.is/", "LoadStatisticsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/statistics?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOADSTATISTICSSERVICE_WSDL_LOCATION = url;
        LOADSTATISTICSSERVICE_EXCEPTION = e;
    }

    public LoadStatisticsService() {
        super(__getWsdlLocation(), LOADSTATISTICSSERVICE_QNAME);
    }

    public LoadStatisticsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOADSTATISTICSSERVICE_QNAME, features);
    }

    public LoadStatisticsService(URL wsdlLocation) {
        super(wsdlLocation, LOADSTATISTICSSERVICE_QNAME);
    }

    public LoadStatisticsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOADSTATISTICSSERVICE_QNAME, features);
    }

    public LoadStatisticsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoadStatisticsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LoadStatistics
     */
    @WebEndpoint(name = "LoadStatisticsPort")
    public LoadStatistics getLoadStatisticsPort() {
        return super.getPort(new QName("http://soap.statistics.project3.is/", "LoadStatisticsPort"), LoadStatistics.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoadStatistics
     */
    @WebEndpoint(name = "LoadStatisticsPort")
    public LoadStatistics getLoadStatisticsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.statistics.project3.is/", "LoadStatisticsPort"), LoadStatistics.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOADSTATISTICSSERVICE_EXCEPTION!= null) {
            throw LOADSTATISTICSSERVICE_EXCEPTION;
        }
        return LOADSTATISTICSSERVICE_WSDL_LOCATION;
    }

}
