
package artifact;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoadStatistics", targetNamespace = "http://soap.statistics.project3.is/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoadStatistics {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loadStatistics", targetNamespace = "http://soap.statistics.project3.is/", className = "artifact.LoadStatistics_Type")
    @ResponseWrapper(localName = "loadStatisticsResponse", targetNamespace = "http://soap.statistics.project3.is/", className = "artifact.LoadStatisticsResponse")
    public String loadStatistics();

}
