
package artifact;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TrocaStringService", targetNamespace = "http://exe2/", wsdlLocation = "http://localhost:8082/exe2?wsdl")
public class TrocaStringService
    extends Service
{

    private final static URL TROCASTRINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException TROCASTRINGSERVICE_EXCEPTION;
    private final static QName TROCASTRINGSERVICE_QNAME = new QName("http://exe2/", "TrocaStringService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/exe2?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TROCASTRINGSERVICE_WSDL_LOCATION = url;
        TROCASTRINGSERVICE_EXCEPTION = e;
    }

    public TrocaStringService() {
        super(__getWsdlLocation(), TROCASTRINGSERVICE_QNAME);
    }

    public TrocaStringService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TROCASTRINGSERVICE_QNAME, features);
    }

    public TrocaStringService(URL wsdlLocation) {
        super(wsdlLocation, TROCASTRINGSERVICE_QNAME);
    }

    public TrocaStringService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TROCASTRINGSERVICE_QNAME, features);
    }

    public TrocaStringService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TrocaStringService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TrocaString
     */
    @WebEndpoint(name = "TrocaStringPort")
    public TrocaString getTrocaStringPort() {
        return super.getPort(new QName("http://exe2/", "TrocaStringPort"), TrocaString.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TrocaString
     */
    @WebEndpoint(name = "TrocaStringPort")
    public TrocaString getTrocaStringPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://exe2/", "TrocaStringPort"), TrocaString.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TROCASTRINGSERVICE_EXCEPTION!= null) {
            throw TROCASTRINGSERVICE_EXCEPTION;
        }
        return TROCASTRINGSERVICE_WSDL_LOCATION;
    }

}
