
package is.project3.subscriptions.wsimport;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SubscriptionService", targetNamespace = "http://subscriptions.project3.is/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SubscriptionService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeSubscription", targetNamespace = "http://subscriptions.project3.is/", className = "is.project3.subscriptions.wsimport.RemoveSubscription")
    @ResponseWrapper(localName = "removeSubscriptionResponse", targetNamespace = "http://subscriptions.project3.is/", className = "is.project3.subscriptions.wsimport.RemoveSubscriptionResponse")
    public boolean removeSubscription(
        @WebParam(name = "arg0", targetNamespace = "")
        Subscription arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<is.project3.subscriptions.wsimport.Subscription>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listSubscriptions", targetNamespace = "http://subscriptions.project3.is/", className = "is.project3.subscriptions.wsimport.ListSubscriptions")
    @ResponseWrapper(localName = "listSubscriptionsResponse", targetNamespace = "http://subscriptions.project3.is/", className = "is.project3.subscriptions.wsimport.ListSubscriptionsResponse")
    public List<Subscription> listSubscriptions(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addSubscription", targetNamespace = "http://subscriptions.project3.is/", className = "is.project3.subscriptions.wsimport.AddSubscription")
    @ResponseWrapper(localName = "addSubscriptionResponse", targetNamespace = "http://subscriptions.project3.is/", className = "is.project3.subscriptions.wsimport.AddSubscriptionResponse")
    public boolean addSubscription(
        @WebParam(name = "arg0", targetNamespace = "")
        Subscription arg0);

}
