
package is.project3.subscriptions.wsimport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SubscriptionServiceService", targetNamespace = "http://subscriptions.project3.is/", wsdlLocation = "http://localhost:8081/soap/subscriptions?wsdl")
public class SubscriptionServiceService
    extends Service
{

    private final static URL SUBSCRIPTIONSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SUBSCRIPTIONSERVICESERVICE_EXCEPTION;
    private final static QName SUBSCRIPTIONSERVICESERVICE_QNAME = new QName("http://subscriptions.project3.is/", "SubscriptionServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/soap/subscriptions?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUBSCRIPTIONSERVICESERVICE_WSDL_LOCATION = url;
        SUBSCRIPTIONSERVICESERVICE_EXCEPTION = e;
    }

    public SubscriptionServiceService() {
        super(__getWsdlLocation(), SUBSCRIPTIONSERVICESERVICE_QNAME);
    }

    public SubscriptionServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUBSCRIPTIONSERVICESERVICE_QNAME, features);
    }

    public SubscriptionServiceService(URL wsdlLocation) {
        super(wsdlLocation, SUBSCRIPTIONSERVICESERVICE_QNAME);
    }

    public SubscriptionServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUBSCRIPTIONSERVICESERVICE_QNAME, features);
    }

    public SubscriptionServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubscriptionServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SubscriptionService
     */
    @WebEndpoint(name = "SubscriptionServicePort")
    public SubscriptionService getSubscriptionServicePort() {
        return super.getPort(new QName("http://subscriptions.project3.is/", "SubscriptionServicePort"), SubscriptionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubscriptionService
     */
    @WebEndpoint(name = "SubscriptionServicePort")
    public SubscriptionService getSubscriptionServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://subscriptions.project3.is/", "SubscriptionServicePort"), SubscriptionService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUBSCRIPTIONSERVICESERVICE_EXCEPTION!= null) {
            throw SUBSCRIPTIONSERVICESERVICE_EXCEPTION;
        }
        return SUBSCRIPTIONSERVICESERVICE_WSDL_LOCATION;
    }

}
