SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE IF NOT EXISTS "smartphone" (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VERSION` bigint(20) NOT NULL,
  `TIMESTAMP` bigint(20) NOT NULL,
  `CRAWLER` varchar(100) NOT NULL,
  `URL` varchar(200) NOT NULL,
  `TITLE` varchar(100) NOT NULL,
  `PRICE` double NOT NULL,
  `PROCESSOR` varchar(200) DEFAULT NULL,
  `SCREENTYPE` varchar(200) DEFAULT NULL,
  `SCREENSIZE` varchar(200) DEFAULT NULL,
  `OTHER` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID` (`ID`)
) ;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
