
package artifact;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TrocaString", targetNamespace = "http://exe2/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TrocaString {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "troca", targetNamespace = "http://exe2/", className = "artifact.Troca")
    @ResponseWrapper(localName = "trocaResponse", targetNamespace = "http://exe2/", className = "artifact.TrocaResponse")
    public String troca(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
